version: '3.8'

services:
  frontend:
    build:
      context: .
      target: production
    container_name: customer_portal_prod
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
    env_file:
      - .env.prod
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    networks:
      - frontend_prod

networks:
  frontend_prod:
    driver: bridge
