version: '3.8'

services:
  frontend:
    build:
      context: .
      target: development
    container_name: customer_portal_dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - frontend_modules_debug:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    stdin_open: true
    tty: true
    networks:
      - frontend_dev

networks:
  frontend_dev:
    driver: bridge
